/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CanBo;
import model.DBThongKe;
import model.PrintPDF;

/**
 *
 * @author Admin
 */
public class CanBoNam extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel;
    DBThongKe dBThongKe;
    SimpleDateFormat dateFormat;
    PrintPDF printPDF;
    ArrayList<CanBo> listCanBo;
    ArrayList<CanBo> listCanBoSVeHuu;

    /**
     * Creates new form DeMo
     */
    public CanBoNam() {
         initComponents();
        listCanBo = new ArrayList<>();
        defaultTableModel = new DefaultTableModel();
        dBThongKe = new DBThongKe();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        printPDF = new PrintPDF();
        loadNameColum();
        loadDataTable();
    }

    public void loadNameColum() {
        ArrayList<String> columnName = new ArrayList<>();
        columnName.add("STT");
        columnName.add("Mã cán bộ");
        columnName.add("Họ và tên");
        columnName.add("Ngày sinh");
        columnName.add("SĐT");
        defaultTableModel.setColumnIdentifiers(columnName.toArray());
        jTable1.setModel(defaultTableModel);
    }

    public void loadDataTable() {
        defaultTableModel.setRowCount(0);

        String nam = jcbNam.getSelectedItem().toString();
        listCanBo = dBThongKe.thongKeGioTinh(0, Integer.parseInt(nam));
        jlTongNhanVien.setText(listCanBo.size() + "");
        if (listCanBo != null) {

            ArrayList<Object> listColumnRow = new ArrayList<>();
            for (int i = 0; i < listCanBo.size(); i++) {
                listColumnRow.add(i + 1);
                listColumnRow.add(listCanBo.get(i).getMaCB());
                listColumnRow.add(listCanBo.get(i).getHoTen());
                listColumnRow.add(dateFormat.format(listCanBo.get(i).getNgaySinh()));
                listColumnRow.add(listCanBo.get(i).getSDT());
                defaultTableModel.addRow(listColumnRow.toArray());
                listColumnRow.clear();
            }
            jTable1.setModel(defaultTableModel);
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi khi truy nhập cơ sở dữ liệu ", "Thông báo ", JOptionPane.WARNING_MESSAGE);
        }
        canBoNghiHuu();

    }
    public void canBoNghiHuu() {
        listCanBoSVeHuu = new ArrayList<>();
        int namHienTai = Integer.parseInt(jcbNam.getSelectedItem().toString());
        for (int i = 0; i < listCanBo.size(); i++) {

            int namSinh = dBThongKe.getYear(listCanBo.get(i).getNgaySinh());
            int tuoi = namHienTai - namSinh;
            if (tuoi > 45 && tuoi < 50) {
                listCanBoSVeHuu.add(listCanBo.get(i));
            }
        }
        jlCanBoScVeHuu.setText((listCanBoSVeHuu.size()) + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcbNam = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jlTongNhanVien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlCanBoScVeHuu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbInThongKe = new javax.swing.JButton();
        jbChiTiet = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Năm : ");

        jcbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2015", "2014", "2013", "2012", "2011" }));
        jcbNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNamItemStateChanged(evt);
            }
        });

        jLabel2.setText("Tổng số nhân viên :");

        jlTongNhanVien.setText("Đây là số lượng nhân viên");

        jLabel4.setText("Tổng số nhân viên sắp về hưu : ");

        jlCanBoScVeHuu.setText("Số nhân viên sắp về hưu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thống kê cán bộ nam");

        jbInThongKe.setText("In thống kê");
        jbInThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInThongKeActionPerformed(evt);
            }
        });

        jbChiTiet.setText("Chi tiết");
        jbChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTongNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCanBoScVeHuu)
                                .addGap(18, 18, 18)
                                .addComponent(jbChiTiet)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jbInThongKe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlTongNhanVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlCanBoScVeHuu)
                            .addComponent(jbChiTiet))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbInThongKe)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbInThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInThongKeActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            int a = fileChooser.showSaveDialog(this);
            if (a == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                printPDF.inThongKeCanBo(listCanBo, file.getPath(), jcbNam.getSelectedItem().toString().trim(), 0,jlTongNhanVien.getText(), jlCanBoScVeHuu.getText());
            }
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_jbInThongKeActionPerformed

    private void jcbNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNamItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            loadDataTable();
        }
    }//GEN-LAST:event_jcbNamItemStateChanged

    private void jbChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChiTietActionPerformed
        // TODO add your handling code here:
        if (listCanBoSVeHuu.size() > 0) {
            CanBoSapVeHuu boSapVeHuu = new CanBoSapVeHuu(listCanBoSVeHuu);
        } else {
            JOptionPane.showMessageDialog(null, "Khong co can bo nao sap ve huu");
        }
    }//GEN-LAST:event_jbChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbChiTiet;
    private javax.swing.JButton jbInThongKe;
    private javax.swing.JComboBox<String> jcbNam;
    private javax.swing.JLabel jlCanBoScVeHuu;
    private javax.swing.JLabel jlTongNhanVien;
    // End of variables declaration//GEN-END:variables
}
