/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBThongKe;
import model.PrintPDF;

/**
 *
 * @author Admin
 */
public class DangPhi extends javax.swing.JPanel {



    DefaultTableModel defaultTableModel;
    DBThongKe dBThongKe;
    SimpleDateFormat dateFormat;
    ArrayList<String> listDataTable;
    PrintPDF printPDF;
    public static final double LUONG_CO_BAN = 12000000;

    /**
     * Creates new form DoanPhi
     */
    public DangPhi() {
        initComponents();
        printPDF = new PrintPDF();
        defaultTableModel = new DefaultTableModel();
        loadNameColumn();
        listDataTable = new ArrayList<>();
        dBThongKe = new DBThongKe();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        loadDataTable();

    }

    public void loadNameColumn() {
        ArrayList<String> nameColumn = new ArrayList<>();
        nameColumn.add("STT");
        nameColumn.add("MS Cán bộ");
        nameColumn.add("Họ và tên");
        nameColumn.add("Ngày sinh");
        nameColumn.add("Chức vụ");
        nameColumn.add("Đảng phí");
        defaultTableModel.setColumnIdentifiers(nameColumn.toArray());
        jTable1.setModel(defaultTableModel);
    }

    public void loadDataTable() {
        listDataTable = new ArrayList<>();
        defaultTableModel.setRowCount(0);
        ResultSet resultSet = dBThongKe.getResultSetDangVien(jcbNam.getSelectedItem().toString());
        if (resultSet == null) {
            System.out.println("null roi");
        }
        ArrayList<String> listRow = new ArrayList<>();
        double tongDangPhi = 0;
        try {

            int i = 0;
            while (resultSet.next()) {

                listRow.add((i + 1) + "");
                listDataTable.add((i + 1) + "");
                listRow.add(resultSet.getString(1));
                listDataTable.add(resultSet.getString(1));
                listRow.add(resultSet.getString(2));
                listDataTable.add(resultSet.getString(2));
                listRow.add(dateFormat.format(resultSet.getDate(3)));
                listDataTable.add(dateFormat.format(resultSet.getDate(3)));
                listRow.add(resultSet.getString(5));
                listDataTable.add(resultSet.getString(5));
                double hsluong = resultSet.getDouble(4);
                double pccv = resultSet.getDouble(6);
                double pcgd = resultSet.getDouble(7);
                double dangPhi = (hsluong + pccv + pcgd) * LUONG_CO_BAN / 100;
                tongDangPhi += dangPhi;
                listRow.add(dangPhi + "");
                listDataTable.add(dangPhi + "");
                defaultTableModel.addRow(listRow.toArray());

                listRow.clear();
                i++;

            }
            jlTongDangVien.setText(i + "");
            jlTongDanPhi.setText(tongDangPhi + "");

        } catch (SQLException ex) {
            Logger.getLogger(DangPhi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlTongDangVien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTongDanPhi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbNam = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbInThongKe = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tổng số đảng viên :");

        jlTongDangVien.setText("Đây là số đoàn viên");

        jLabel3.setText("Tổng đảng  phí : ");

        jlTongDanPhi.setText("Đây là tổng đoàn phí");

        jLabel5.setText("Năm : ");

        jcbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2015", "2014", "2013", "2012", "2011" }));
        jcbNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNamItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Danh sách đảng viên");

        jbInThongKe.setText("In thống kê");
        jbInThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTongDanPhi)
                                    .addComponent(jlTongDangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbInThongKe)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlTongDangVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlTongDanPhi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jbInThongKe)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNamItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            loadDataTable();
        }
    }//GEN-LAST:event_jcbNamItemStateChanged

    private void jbInThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInThongKeActionPerformed
        // TODO add your handling code here:
        if( listDataTable.size() > 0){
         try {
            JFileChooser fileChooser = new JFileChooser();
            int a = fileChooser.showSaveDialog(this);
            if (a == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
               
                printPDF.thongKeDangPhi(listDataTable, file.getPath(), jcbNam.getSelectedItem().toString(), jlTongDangVien.getText());
                
            }
        } catch (NullPointerException e) {

        }
         
        }
        else JOptionPane.showMessageDialog(null, "Danh sách không có đoàn viên nào cả ", "Thông báo ", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jbInThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbInThongKe;
    private javax.swing.JComboBox<String> jcbNam;
    private javax.swing.JLabel jlTongDanPhi;
    private javax.swing.JLabel jlTongDangVien;
    // End of variables declaration//GEN-END:variables
}
