/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBThongKe;
import model.PrintPDF;

/**
 *
 * @author Admin
 */
public class DoanPhi extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel;
    DBThongKe dBThongKe;
    SimpleDateFormat dateFormat;
    ArrayList<String> listDataTable;
    PrintPDF printPDF;

    /**
     * Creates new form DoanPhi
     */
    public DoanPhi() {
        initComponents();
        printPDF  = new PrintPDF();
        dBThongKe = new DBThongKe();
        defaultTableModel = new DefaultTableModel();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        loadColumnName();
        loadDataTable();
    }
    public void loadColumnName(){
        ArrayList<String> nameColum = new ArrayList<>();
        nameColum.add("STT");
        nameColum.add("Mã cán bộ");
        nameColum.add("Họ và tên");
        nameColum.add("Ngày sinh");
        nameColum.add("Số tài khoản");
        defaultTableModel.setColumnIdentifiers(nameColum.toArray());
//        jTable1.setModel(defaultTableModel);
    }
    public void loadDataTable(){
        defaultTableModel.setRowCount(0);
        ArrayList<String> listRow = new ArrayList();
        listDataTable = new ArrayList<>();
        try {
            ResultSet resultSet = dBThongKe.getResultSetDoanVien(jcbNam.getSelectedItem().toString());
            int i = 0;
            while( resultSet.next()){
                listRow.add((i + 1)  +"");
                listDataTable.add((i + 1)  +"");
                listRow.add(resultSet.getString(1));
                listDataTable.add(resultSet.getString(1));
                listRow.add(resultSet.getString(2));
                listDataTable.add(resultSet.getString(2));
                Date d = resultSet.getDate(3);
                String ngaySinh = dateFormat.format(d);
                listRow.add(ngaySinh);
                listDataTable.add(ngaySinh);
                listRow.add(resultSet.getString(4));
                listDataTable.add(resultSet.getString(4));
                defaultTableModel.addRow(listRow.toArray());
                listRow.clear();
                i++;
            }
            jlTongSoDoanVien.setText(i +"");
            System.out.println("size cua listdata : " + listDataTable.size());
        } catch (SQLException ex) {
            Logger.getLogger(DoanPhi.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlTongSoDoanVien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbNam = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfDoanPhi = new javax.swing.JTextField();
        jbInThongKe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tổng số đoàn viên :");

        jlTongSoDoanVien.setText("Đây là số đoàn viên");

        jLabel3.setText("Đoàn phí : ");

        jLabel5.setText("Năm : ");

        jcbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2015", "2014", "2013", "2012", "2011", "2010", " " }));
        jcbNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNamItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thống kê đoàn viên");

        jbInThongKe.setText("In thống kê");
        jbInThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInThongKeActionPerformed(evt);
            }
        });

        jLabel2.setText("VND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 541, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlTongSoDoanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jtfDoanPhi))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbInThongKe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlTongSoDoanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDoanPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbInThongKe)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNamItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            loadDataTable();
        }
    }//GEN-LAST:event_jcbNamItemStateChanged

    private void jbInThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInThongKeActionPerformed
        // TODO add your handling code here:
        
        if( listDataTable.size() > 0){
         try {
            JFileChooser fileChooser = new JFileChooser();
            int a = fileChooser.showSaveDialog(this);
            if (a == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                printPDF.thongKeDoanPhi(listDataTable, file.getPath(), jcbNam.getSelectedItem().toString(), jlTongSoDoanVien.getText(), jtfDoanPhi.getText());
            }
        } catch (NullPointerException e) {

        }
         
        }
        else JOptionPane.showMessageDialog(null, "Danh sách không có đoàn viên nào cả ", "Thông báo ", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jbInThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbInThongKe;
    private javax.swing.JComboBox<String> jcbNam;
    private javax.swing.JLabel jlTongSoDoanVien;
    private javax.swing.JTextField jtfDoanPhi;
    // End of variables declaration//GEN-END:variables
}
