/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.DBhsLuong;
import model.HeSoLuong;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.CanBo;
/**
 *
 * @author Windows 10
 */
public class HienThi_HSLuong extends javax.swing.JFrame {
    //Khởi tạo dữ liệu
    ArrayList<HeSoLuong> arrayList;
    DBhsLuong dBhsLuong;
    DefaultTableModel defaultTableModel;
    SimpleDateFormat dateFormat;
    int IdChucVu;
    int size;
    /**
     * Creates new form HienThi_HSLuong
     */
    public HienThi_HSLuong(CanBo canbo) {
        initComponents();
        String maCB = canbo.getMaCB();
        jLabel_MaCB.setText(maCB);
        defaultTableModel = new DefaultTableModel();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        dBhsLuong = new DBhsLuong();
        arrayList = dBhsLuong.getAll(maCB);
        size = arrayList.size();
        ArrayList<HeSoLuong> list = dBhsLuong.getAllCanBo();
        //ID để tính cho vị trí tiếp theo chèn vào sẽ không bị trùng
        IdChucVu = list.get(list.size() - 1).getIdhesoluong() + 1;
        loadNameColumn();
        loadDataTable(arrayList);
        this.setResizable(false);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    //Tên các cột trong bảng 
    private void loadNameColumn() {
        ArrayList<String> listColumnName = new ArrayList<>();
        listColumnName.add("STT");
        listColumnName.add("Hệ Số Lương");
        listColumnName.add("Ngày bắt đầu");
        defaultTableModel.setColumnIdentifiers(listColumnName.toArray());
    }
    //load data lên bảng
    private void loadDataTable(ArrayList<HeSoLuong> al) {
        IdChucVu++;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //Làm mới bảng
        defaultTableModel.setRowCount(0);

        ArrayList<Object> listRow = new ArrayList<>();
        if (al != null) {
            for (int i = 0; i < al.size(); i++) {
                listRow.add(i + 1);
                listRow.add(al.get(i).getHsluong());
                Date date = al.get(i).getThoiGianBD();
                String thoiGianBD = dateFormat.format(date);
                listRow.add(thoiGianBD);
                defaultTableModel.addRow(listRow.toArray());
                listRow.clear();
            }
            jTable_ChucVu.setModel(defaultTableModel);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_TGBD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_PCChucVu = new javax.swing.JLabel();
        jTextField_HSLuong = new javax.swing.JTextField();
        jButton_Sua = new javax.swing.JButton();
        jButton_Dong = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_MaCB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChucVu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_TGBD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Thời gian bắt đầu:");

        jLabel_PCChucVu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_PCChucVu.setText("Hệ Số Lương:");

        jTextField_HSLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_Sua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Dong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Dong.setText("Đóng");
        jButton_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DongActionPerformed(evt);
            }
        });

        jButton_Them.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã Cán Bộ");

        jLabel_MaCB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_MaCB.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_PCChucVu)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(21, 21, 21)))
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton_Dong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MaCB)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_HSLuong)
                                .addComponent(jTextField_TGBD, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_MaCB))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PCChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Dong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTable_ChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_ChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_ChucVu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        int index = jTable_ChucVu.getSelectedRow();
        HeSoLuong hsluong_selected = arrayList.get(index);
        double hsLuong = Double.parseDouble(jTextField_HSLuong.getText());
        String tgbd = jTextField_TGBD.getText();
        String maCB = jLabel_MaCB.getText();
        Date thoigianBD = null;
        try {
            thoigianBD = dateFormat.parse(tgbd);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Nhap khong dung dinh dang cua date !!", "Thong bao", JOptionPane.WARNING_MESSAGE);
        }
        //đưa thông tin hệ số lương đang chọn lên các JText_Field
        hsluong_selected.setHsluong(hsLuong);
        hsluong_selected.setThoiGianBD(thoigianBD);
        HeSoLuong result = dBhsLuong.updatehsLuong(hsluong_selected);
        if (result != null) {
            JOptionPane.showMessageDialog(null, "Update thanh cong");
            arrayList = dBhsLuong.getAll(maCB);

            defaultTableModel.setRowCount(0);

            ArrayList<Object> listRow = new ArrayList<>();
            if (arrayList != null) {
                for (int i = 0; i < arrayList.size(); i++) {
                    listRow.add(i + 1);
                    listRow.add(arrayList.get(i).getHsluong());
                    Date date = arrayList.get(i).getThoiGianBD();
                    String thoiGianBD = dateFormat.format(date);
                    listRow.add(thoiGianBD);
                    defaultTableModel.addRow(listRow.toArray());
                    listRow.clear();
                }
                //            jTable1.setModel(defaultTableModel);
            } else {
                JOptionPane.showMessageDialog(null, "Update that bai !!", "Thong bao", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_DongActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        String tgbd = jTextField_TGBD.getText();
        String maCB = jLabel_MaCB.getText();
        double hsLuong = Double.parseDouble(jTextField_HSLuong.getText());
        Date thoigianBD = null;
        try {
            thoigianBD = dateFormat.parse(tgbd);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Nhap khong dung dinh dang cua date !!", "Thong bao", JOptionPane.WARNING_MESSAGE);
        }
        //tạo 1 đối tượng mới
        HeSoLuong hsluong = new HeSoLuong(IdChucVu, maCB, hsLuong, thoigianBD);
        HeSoLuong result = dBhsLuong.addNew(maCB, hsluong);
        if (result != null) {
            JOptionPane.showMessageDialog(null, "Thêm hệ số lương thành công");
            arrayList = dBhsLuong.getAll(maCB);
            loadDataTable(arrayList);

        } else {
            JOptionPane.showMessageDialog(null, "Thêm hệ số lương thất bại");
        }
        //        ArrayList<Object> listRow = new ArrayList<>();
        //        listRow.add(size+1);
        //        listRow.add(chucDanh);
        //        listRow.add(tgbd);
        //        defaultTableModel.addRow(listRow.toArray());;
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        int index = jTable_ChucVu.getSelectedRow();
        String canbo = jLabel_MaCB.getText();
        double hsLuong = Double.parseDouble(jTextField_HSLuong.getText());
        String tgbd = jTextField_TGBD.getText();
        String maCB = jLabel_MaCB.getText();

        if (index >= 0) {
            HeSoLuong hsluong = arrayList.get(index);
            int conf = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dòng  : ID hệ số lương :  " + hsluong.getIdhesoluong(), "Thông báo!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                hsluong = dBhsLuong.deletehsLuong(hsluong);
                if (hsluong != null) {
                    arrayList.remove(index);
                    loadDataTable(arrayList);
                    JOptionPane.showMessageDialog(null, "Xóa thành công !!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để xóa !!", "Thông báo ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTable_ChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ChucVuMouseClicked
        // TODO add your handling code here:
        int index = jTable_ChucVu.getSelectedRow();
        jTextField_HSLuong.setText(String.valueOf(arrayList.get(index).getHsluong()));
        Date date = arrayList.get(index).getThoiGianBD();
        jTextField_TGBD.setText(dateFormat.format(date));
    }//GEN-LAST:event_jTable_ChucVuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienThi_HSLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienThi_HSLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienThi_HSLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienThi_HSLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HienThi_HSLuong().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Dong;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_MaCB;
    private javax.swing.JLabel jLabel_PCChucVu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ChucVu;
    private javax.swing.JTextField jTextField_HSLuong;
    private javax.swing.JTextField jTextField_TGBD;
    // End of variables declaration//GEN-END:variables
}
