/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import model.CanBo;
import model.ChucDanh;
import model.DBCanBo;

/**
 *
 * @author Admin
 */
public class QuanLyThongTin extends javax.swing.JPanel {

    public static int indexQuanLyTT;
    JTabbedPane jTabbedPane;
    //Khởi tạo dữ liệu
    ArrayList<CanBo> arrayList;
    DBCanBo dBCanBo;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form QuanLyMonHoc
     */
    public QuanLyThongTin(JTabbedPane jTabbedPane) {
        initComponents();
        indexQuanLyTT = -1;
        this.jTabbedPane = jTabbedPane;
        indexQuanLyTT = -1;
        editText(false);
        defaultTableModel = new DefaultTableModel();
        dBCanBo = new DBCanBo();
        arrayList = dBCanBo.getAll();
        loadNameColumn();
        loadDataTable(arrayList);
        this.setVisible(true);
        jButton_ChucDanh.setEnabled(false);
        jButton_ChucVu.setEnabled(false);
        jButton_HSLuong.setEnabled(false);
        jButton_DangDoan.setEnabled(false);
        
    }
    //Tên các cột trong bảng 
    private void loadNameColumn() {
        ArrayList<String> listColumnName = new ArrayList<>();
        listColumnName.add("STT");
        listColumnName.add("Mã Cán Bộ");
        listColumnName.add("Họ Tên");
        listColumnName.add("Ngày Sinh");
        listColumnName.add("Giới tính");
        listColumnName.add("Mã Số Thuế");
        listColumnName.add("Số tài khoản");
        listColumnName.add("Địa chỉ");
        listColumnName.add("SĐT");
        listColumnName.add("Email");
        listColumnName.add("PC Giảng dạy");
        listColumnName.add("Thông tin khác");
        listColumnName.add("User level");
        listColumnName.add("Password");
        listColumnName.add("Ngày BD");
        defaultTableModel.setColumnIdentifiers(listColumnName.toArray());
    }
    //
    private void loadDataTable(ArrayList<CanBo> al) {
//        arrayList = dBChamThi.getAll();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //Làm mới bảng
        defaultTableModel.setRowCount(0);

        ArrayList<Object> listRow = new ArrayList<>();
        if (al != null) {
            for (int i = 0; i < al.size(); i++) {
                listRow.add(i + 1);
                listRow.add(al.get(i).getMaCB());
                listRow.add(al.get(i).getHoTen());
                Date date = al.get(i).getNgaySinh();
                String ngaySinh = dateFormat.format(date);
                listRow.add(ngaySinh);
                listRow.add(al.get(i).getGioiTinh());
                listRow.add(al.get(i).getMaSoThue());
                listRow.add(al.get(i).getSoTaiKhoan());
                listRow.add(al.get(i).getDiaChi());
                listRow.add(al.get(i).getSDT());
                listRow.add(al.get(i).getEmail());
                listRow.add(al.get(i).getPCGiangDay());
                listRow.add(al.get(i).getThanhTichKhac());
                listRow.add(al.get(i).getUser_level());
                listRow.add(al.get(i).getPassword());
                Date date1 = al.get(i).getNgayBD();
                String ngayBD = dateFormat.format(date1);
                listRow.add(ngayBD);
                defaultTableModel.addRow(listRow.toArray());
                listRow.clear();
            }
            jTable_QuanLyThongTin.setModel(defaultTableModel);
        }
    }
    //Set text để edit được
    private void editText(boolean a) {
        jtfMaCB.setEnabled(a);
        jtfTenCanBo.setEnabled(a);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbMaCB = new javax.swing.JRadioButton();
        jtfMaCB = new javax.swing.JTextField();
        jrbTenCB = new javax.swing.JRadioButton();
        jtfTenCanBo = new javax.swing.JTextField();
        jbTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton_ChucDanh = new javax.swing.JButton();
        jButton_ChucVu = new javax.swing.JButton();
        jButton_HSLuong = new javax.swing.JButton();
        jButton_DangDoan = new javax.swing.JButton();
        jbThemCanBo = new javax.swing.JButton();
        jbSuaThongTin = new javax.swing.JButton();
        jbXoaCB = new javax.swing.JButton();
        jbChiTiet = new javax.swing.JButton();
        jbCloseTab = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_QuanLyThongTin = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        setLayout(new java.awt.BorderLayout());

        jrbMaCB.setText("Mã Cán Bộ");
        jrbMaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMaCBActionPerformed(evt);
            }
        });

        jrbTenCB.setText("Tên Cán Bộ");
        jrbTenCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTenCBActionPerformed(evt);
            }
        });

        jbTimKiem.setText("Tìm kiếm");
        jbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jrbMaCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jrbTenCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTenCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(jbTimKiem)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMaCB)
                    .addComponent(jtfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbTenCB)
                    .addComponent(jtfTenCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTimKiem))
                .addGap(15, 15, 15))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255)));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        jButton_ChucDanh.setText("Chức Danh");
        jButton_ChucDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChucDanhActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_ChucDanh);

        jButton_ChucVu.setText("Chức vụ");
        jButton_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChucVuActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_ChucVu);

        jButton_HSLuong.setText("HS Lương");
        jButton_HSLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HSLuongActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_HSLuong);

        jButton_DangDoan.setText("Đảng-Đoàn");
        jButton_DangDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangDoanActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_DangDoan);

        jbThemCanBo.setText("Thêm cán bộ");
        jbThemCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemCanBoActionPerformed(evt);
            }
        });
        jPanel5.add(jbThemCanBo);

        jbSuaThongTin.setText("Sửa thông tin");
        jbSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuaThongTinActionPerformed(evt);
            }
        });
        jPanel5.add(jbSuaThongTin);

        jbXoaCB.setText("Xóa cán bộ");
        jbXoaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXoaCBActionPerformed(evt);
            }
        });
        jPanel5.add(jbXoaCB);

        jbChiTiet.setText("Chi tiết");
        jbChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChiTietActionPerformed(evt);
            }
        });
        jPanel5.add(jbChiTiet);

        jbCloseTab.setText("CloseTab");
        jbCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseTabActionPerformed(evt);
            }
        });
        jPanel5.add(jbCloseTab);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jTable_QuanLyThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_QuanLyThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QuanLyThongTinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_QuanLyThongTin);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseTabActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(jTabbedPane.getSelectedIndex());
        indexQuanLyTT = -1;
        GiaoDienChinh.soLuongTab--;
        System.out.println("so luong tab" + GiaoDienChinh.soLuongTab);
    }//GEN-LAST:event_jbCloseTabActionPerformed

    private void jrbMaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMaCBActionPerformed
        // TODO add your handling code here:
        if(jrbMaCB.isSelected()) {
            jtfMaCB.setEnabled(true);
            jtfMaCB.requestFocus();
        } else {
            jtfMaCB.setEnabled(false);
            jtfMaCB.setText("");
        }
    }//GEN-LAST:event_jrbMaCBActionPerformed

    private void jrbTenCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTenCBActionPerformed
        // TODO add your handling code here:
        if(jrbTenCB.isSelected()) {
            jtfTenCanBo.setEnabled(true);
            jtfTenCanBo.requestFocus();
        } else {
            jtfTenCanBo.setEnabled(false);
            jtfTenCanBo.setText("");
        }
    }//GEN-LAST:event_jrbTenCBActionPerformed

    private void jbThemCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemCanBoActionPerformed
        // TODO add your handling code here:
       ThemCanBo  canBo = new ThemCanBo(defaultTableModel);
    }//GEN-LAST:event_jbThemCanBoActionPerformed

    private void jbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTimKiemActionPerformed
        // TODO add your handling code here:
        String maCanBo = jtfMaCB.getText();
        String tenCanBo = jtfTenCanBo.getText();
        String mcb = "%" + maCanBo.trim() + "%";
        String hoTen = "%" + tenCanBo.trim() + "%";
        arrayList = dBCanBo.findBy(mcb,hoTen);
        loadDataTable(arrayList);
        jbChiTiet.setEnabled(false);
    }//GEN-LAST:event_jbTimKiemActionPerformed

    private void jbXoaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXoaCBActionPerformed
        // TODO add your handling code here:
       int index = jTable_QuanLyThongTin.getSelectedRow();
       String maCanBo = jtfMaCB.getText();
       String tenCanBo = jtfTenCanBo.getText();
       String mcb = "%" + maCanBo.trim() + "%";
       String tencb = "%" + tenCanBo.trim() + "%";
       arrayList = dBCanBo.findBy(mcb, tencb);

        if (index >= 0) {
            CanBo canBo = arrayList.get(index);
            int conf = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dòng  : Mã Cán Bộ :  " + canBo.getMaCB() + "Tên Cán bộ  =  " + canBo.getHoTen(), "Thông báo!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                canBo = dBCanBo.deleteCanBo(canBo);
                if (canBo != null) {
                    arrayList.remove(index);
                    loadDataTable(arrayList);
                    JOptionPane.showMessageDialog(null, "Xóa thành công !!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để xóa !!", "Thông báo ", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_jbXoaCBActionPerformed

    private void jbSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuaThongTinActionPerformed
        // TODO add your handling code here:
         int index = jTable_QuanLyThongTin.getSelectedRow();

        if (index >= 0) {
            String maCanBo = jtfMaCB.getText();
            String tenCB = jtfTenCanBo.getText();
            String mcb = "%" + maCanBo.trim() + "%";
            String tencb = "%" + tenCB.trim() + "%";
            //Tại sao mỗi lần thêm sửa thì lại phải tìm kiếm ???
            arrayList = dBCanBo.findBy(mcb, tencb);
            System.out.println(arrayList.size());
            CanBo canBo = arrayList.get(index);
            new SuaCanBo(defaultTableModel, canBo, mcb, tencb);

        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hàng nào để sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }       
    }//GEN-LAST:event_jbSuaThongTinActionPerformed

    private void jTable_QuanLyThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QuanLyThongTinMouseClicked
        // TODO add your handling code here:
        jButton_ChucDanh.setEnabled(true);
        jButton_ChucVu.setEnabled(true);
        jButton_HSLuong.setEnabled(true);
        jButton_DangDoan.setEnabled(true);
        
    }//GEN-LAST:event_jTable_QuanLyThongTinMouseClicked

    private void jButton_ChucDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChucDanhActionPerformed
        // TODO add your handling code here:
        arrayList = dBCanBo.getAll();
        int index = jTable_QuanLyThongTin.getSelectedRow();
        if(index >= 0){
            CanBo canBo = arrayList.get(index);
            new HienThi_ChucDanh(canBo);
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hàng nào để thêm chức danh!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ChucDanhActionPerformed

    private void jbChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChiTietActionPerformed
        // TODO add your handling code here:
        int index = jTable_QuanLyThongTin.getSelectedRow();
        CanBo canBo = arrayList.get(index);
        
        ThongTinChiTiet.canBo = canBo;
        ThongTinChiTiet chiTiet = new  ThongTinChiTiet();
    }//GEN-LAST:event_jbChiTietActionPerformed

    private void jButton_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChucVuActionPerformed
        // TODO add your handling code here:
        arrayList = dBCanBo.getAll();
        int index = jTable_QuanLyThongTin.getSelectedRow();
        if(index >= 0){
            CanBo canBo = arrayList.get(index);
            new HienThi_ChucVu(canBo);
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hàng nào để thêm chức vụ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ChucVuActionPerformed

    private void jButton_HSLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HSLuongActionPerformed
        // TODO add your handling code here:
        arrayList = dBCanBo.getAll();
        int index = jTable_QuanLyThongTin.getSelectedRow();
        if(index >= 0){
            CanBo canBo = arrayList.get(index);
            new HienThi_HSLuong(canBo);
        }
    }//GEN-LAST:event_jButton_HSLuongActionPerformed

    private void jButton_DangDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangDoanActionPerformed
        // TODO add your handling code here:
        arrayList = dBCanBo.getAll();
        int index = jTable_QuanLyThongTin.getSelectedRow();
        if(index >= 0){
            CanBo canBo = arrayList.get(index);
            new HienThi_DangDoan(canBo);
        }
    }//GEN-LAST:event_jButton_DangDoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ChucDanh;
    private javax.swing.JButton jButton_ChucVu;
    private javax.swing.JButton jButton_DangDoan;
    private javax.swing.JButton jButton_HSLuong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_QuanLyThongTin;
    private javax.swing.JButton jbChiTiet;
    private javax.swing.JButton jbCloseTab;
    private javax.swing.JButton jbSuaThongTin;
    private javax.swing.JButton jbThemCanBo;
    private javax.swing.JButton jbTimKiem;
    private javax.swing.JButton jbXoaCB;
    private javax.swing.JRadioButton jrbMaCB;
    private javax.swing.JRadioButton jrbTenCB;
    private javax.swing.JTextField jtfMaCB;
    private javax.swing.JTextField jtfTenCanBo;
    // End of variables declaration//GEN-END:variables
}
