/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CanBo;
import model.DBDeTaiNghienCuu;
import model.DeTaiNghienCuu;

/**
 *
 * @author tu
 */
public class SuaDeTai extends javax.swing.JFrame {

    /**
     * Creates new form SuaDeTai
     */
    public static Vector<String> hangDuLieu;
    public DeTaiNghienCuu deTaiCu;

    public SuaDeTai() {
        this.setVisible(true);
        this.setTitle("Sua");
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        khoiTaoNoiDung();
    }

    public void khoiTaoNoiDung() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        String maDeTai = hangDuLieu.get(0);
        String maCanBo = hangDuLieu.get(1);
        String tenDeTai = hangDuLieu.get(2);
        String cap = hangDuLieu.get(3);
        Double kinhPhi = Double.parseDouble(hangDuLieu.get(4));
        Date ngayBatDau = null;
        Date ngayKetThuc = null;
        try {
            ngayBatDau = dateFormat.parse(hangDuLieu.get(5));
            ngayKetThuc = dateFormat.parse(hangDuLieu.get(6));
        } catch (ParseException ex) {
            Logger.getLogger(SuaDeTai.class.getName()).log(Level.SEVERE, null, ex);
        }
        String chuTriDeTai = hangDuLieu.get(7);
        String ketQua = hangDuLieu.get(8);
        deTaiCu = new DeTaiNghienCuu(maDeTai, maCanBo, tenDeTai, cap, kinhPhi, ngayBatDau, ngayKetThuc, chuTriDeTai, ketQua);

        txtMaDeTai.setText(maDeTai);
        txtMaCB.setText(maCanBo);
        txtTenDeTai.setText(tenDeTai);
        txtCap.setText(cap);
        txtKinhPhi.setText(String.valueOf(kinhPhi));
        txtNgayBatDau.setText(dateFormat.format(ngayBatDau));
        txtNgayKetThuc.setText(dateFormat.format(ngayKetThuc));
        txtChuTri.setText(chuTriDeTai);
        txtKetQua.setText(ketQua);
    }

    public void suaDeTai() {
        String maDeTai = txtMaDeTai.getText().trim();
        String maCB = txtMaCB.getText().trim();
        String tenDT = txtTenDeTai.getText().trim();
        String kinhPhiStr = txtKinhPhi.getText().trim();
        String cap = txtCap.getText().trim();
        String batDauStr = txtNgayBatDau.getText().trim();
        String ketThucStr = txtNgayKetThuc.getText().trim();
        String chuTri = txtChuTri.getText().trim();
        String ketQua = txtKetQua.getText().trim();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        java.util.Date ngayBatDau = null;
        java.util.Date ngayKetThuc = null;
        Double kinhPhi = 0d;

        try {
            ngayBatDau = dateFormat.parse(batDauStr);
            ngayKetThuc = dateFormat.parse(ketThucStr);
            kinhPhi = Double.parseDouble(kinhPhiStr);

            if (maDeTai.length() < 3
                    || tenDT.length() < 3
                    || cap.length() < 3
                    || chuTri.length() < 3
                    || ketQua.length() < 3) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Thong tin nhap vao chua hop le !");
            return;
        }
        
        DeTaiNghienCuu deTaiMoi = new DeTaiNghienCuu(maDeTai, maCB, tenDT, cap, kinhPhi, ngayBatDau, ngayKetThuc, chuTri, ketQua);
        DBDeTaiNghienCuu bDeTaiNghienCuu = new DBDeTaiNghienCuu();
        if (bDeTaiNghienCuu.updateDeTai(deTaiCu, deTaiMoi) > 0){
            JOptionPane.showMessageDialog(rootPane, "Cap Nhat Thanh Cong !");
            return;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Cap nhat khong thanh cong !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSuaDeTai = new javax.swing.JButton();
        txtMaDeTai = new javax.swing.JTextField();
        txtMaCB = new javax.swing.JTextField();
        txtTenDeTai = new javax.swing.JTextField();
        txtKinhPhi = new javax.swing.JTextField();
        txtCap = new javax.swing.JTextField();
        txtNgayBatDau = new javax.swing.JTextField();
        txtNgayKetThuc = new javax.swing.JTextField();
        txtChuTri = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SỬA ĐỀ TÀI");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã Đề Tài : ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Mã CB : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tên Đề Tài : ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Kinh Phí :  ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Cấp : ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Ngày Bắt Đầu : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Ngày Kết Thúc :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Chủ Trì : ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Kết Quả : ");

        btnSuaDeTai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaDeTai.setText("Sửa");
        btnSuaDeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDeTaiActionPerformed(evt);
            }
        });

        txtMaDeTai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMaCB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTenDeTai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtKinhPhi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtCap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNgayBatDau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNgayKetThuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtChuTri.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtKetQua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSuaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(txtMaDeTai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNgayKetThuc)
                                    .addComponent(txtChuTri)
                                    .addComponent(txtMaCB)
                                    .addComponent(txtTenDeTai)
                                    .addComponent(txtKinhPhi)
                                    .addComponent(txtCap)
                                    .addComponent(txtNgayBatDau))
                                .addGap(6, 6, 6)))))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtChuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnSuaDeTai)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaDeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDeTaiActionPerformed
        // TODO add your handling code here:
        suaDeTai();
    }//GEN-LAST:event_btnSuaDeTaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaDeTai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaDeTai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtChuTri;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtMaCB;
    private javax.swing.JTextField txtMaDeTai;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtTenDeTai;
    // End of variables declaration//GEN-END:variables
}
