/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import model.CanBo;
import model.DBTimKiem;

/**
 *
 * @author Admin
 */
public class TimKiem extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
   public static  int indexTimKiem;
    JTabbedPane jTabbedPane;
    DefaultTableModel defaultTableModel;
    DBTimKiem dBTimKiem;
    SimpleDateFormat dateFormat;

    /**
     * Creates new form TimKiem
     */
    public TimKiem(JTabbedPane jTabbedPane) {
        initComponents();
        jtfMaCB.setEnabled(false);
        jtfTen.setEnabled(false);
        jcbGioiTinh.setEnabled(false);
        dateFormat =new SimpleDateFormat("dd/MM/yyyy");
        dBTimKiem = new DBTimKiem();
        indexTimKiem = -1;
        this.jTabbedPane = jTabbedPane;
        defaultTableModel = new DefaultTableModel();
        loadNameColumn();
        loadDataColum();
    }

    public void loadNameColumn() {
        ArrayList<String> listNameColum = new ArrayList<>();
        listNameColum.add("STT");
        listNameColum.add("Mã cán bộ");
        listNameColum.add("Họ và tên");
        listNameColum.add("Ngày sinh");
        listNameColum.add("Giới tính");
        listNameColum.add("Mã số thuế");
        listNameColum.add("Số tài khoản");
        listNameColum.add("Địa chỉ");
        listNameColum.add("Số điện thoại");
        listNameColum.add("Email");
        listNameColum.add("Thành tích khác");
        listNameColum.add("Ngày bắt đầu");
        defaultTableModel.setColumnIdentifiers(listNameColum.toArray());
        jTable1.setModel(defaultTableModel);
    }

    public void loadDataColum() {
        defaultTableModel.setRowCount(0);
        String macb = "%" + jtfMaCB.getText().trim() + "%";
        String ten = "%" + jtfTen.getText().trim() + "%";
        String gioiTinh = "";
        if (jrGioiTinh.isSelected()) {
            int index = jcbGioiTinh.getSelectedIndex();
            gioiTinh = "%" + index + "%";
        } else {
            gioiTinh = "%";
        }

        ArrayList<CanBo> listCanBo = dBTimKiem.timKiemCanBo(macb, ten, gioiTinh);
        if (listCanBo != null) {
            System.out.println("den chona");
            ArrayList<String> rowTable = new ArrayList<>();
            for (int i = 0; i < listCanBo.size(); i++) {
                rowTable.add((i + 1) + "");
                rowTable.add(listCanBo.get(i).getMaCB());
                rowTable.add(listCanBo.get(i).getHoTen());
                Date date = listCanBo.get(i).getNgaySinh();
                String nSinh = dateFormat.format(date);
                rowTable.add(nSinh);
                int gioitinh  = listCanBo.get(i).getGioiTinh();
                String gTinh = "";
                if(gioitinh == 0) gTinh ="Nam ";
                else if(gioitinh == 1) gTinh ="Nữ";
                rowTable.add(gTinh);
                rowTable.add(listCanBo.get(i).getMaSoThue());
                rowTable.add(listCanBo.get(i).getSoTaiKhoan());
                rowTable.add(listCanBo.get(i).getDiaChi());
                rowTable.add(listCanBo.get(i).getSDT());
                rowTable.add(listCanBo.get(i).getEmail());
                String thanhTichKhac = listCanBo.get(i).getThanhTichKhac();
                if(thanhTichKhac ==  null) thanhTichKhac= "";
                rowTable.add(thanhTichKhac);
                Date dateBD = listCanBo.get(i).getNgayBD();
                String ngaBD = dateFormat.format(dateBD);
                rowTable.add(ngaBD);
                defaultTableModel.addRow(rowTable.toArray());
                rowTable.clear();
                                          
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrMaCB = new javax.swing.JRadioButton();
        jrTen = new javax.swing.JRadioButton();
        jtfMaCB = new javax.swing.JTextField();
        jtfTen = new javax.swing.JTextField();
        jcbGioiTinh = new javax.swing.JComboBox<>();
        jrGioiTinh = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbCloseTab = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jrMaCB.setText("Mã Cán bộ");
        jrMaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMaCBActionPerformed(evt);
            }
        });

        jrTen.setText("Tên");
        jrTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTenActionPerformed(evt);
            }
        });

        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jcbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGioiTinhActionPerformed(evt);
            }
        });

        jrGioiTinh.setText("giới tính");
        jrGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrGioiTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfMaCB)
                    .addComponent(jrMaCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrTen)
                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMaCB)
                    .addComponent(jrTen)
                    .addComponent(jrGioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbCloseTab.setText("CloseTab");
        jbCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseTabActionPerformed(evt);
            }
        });
        jPanel6.add(jbCloseTab);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGioiTinhActionPerformed

    private void jbCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseTabActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(jTabbedPane.getSelectedIndex());
        indexTimKiem = -1;
        GiaoDienChinh.soLuongTab--;
        System.out.println("so luong tab" + GiaoDienChinh.soLuongTab);
    }//GEN-LAST:event_jbCloseTabActionPerformed

    private void jrMaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMaCBActionPerformed
        // TODO add your handling code here:
        if(jrMaCB.isSelected()){
            jtfMaCB.setEnabled(true);
            jtfMaCB.requestFocus();
        }else{
            jtfMaCB.setEnabled(false);
            jtfMaCB.setText("");
        }
    }//GEN-LAST:event_jrMaCBActionPerformed

    private void jrTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTenActionPerformed
        // TODO add your handling code here:
        if(jrTen.isSelected()){
            jtfTen.setEnabled(true);
            jtfTen.requestFocus();
        }else{
            jtfTen.setEnabled(false);
            jtfTen.setText("");
        }
    }//GEN-LAST:event_jrTenActionPerformed

    private void jrGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrGioiTinhActionPerformed
        // TODO add your handling code here:
        if(jrGioiTinh.isSelected()){
            jcbGioiTinh.setEnabled(true);
        }
        else jcbGioiTinh.setEnabled(false);
    }//GEN-LAST:event_jrGioiTinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadDataColum();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCloseTab;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JRadioButton jrGioiTinh;
    private javax.swing.JRadioButton jrMaCB;
    private javax.swing.JRadioButton jrTen;
    private javax.swing.JTextField jtfMaCB;
    private javax.swing.JTextField jtfTen;
    // End of variables declaration//GEN-END:variables
}
